[versions]
agp = "8.13.1"
annotation = "1.9.1"
annotations = "26.0.2-1"
cardview = "1.0.0"
core = "1.17.0"
exoplayer = "2.19.1"
fragment = "1.8.9"
jaudiotagger = "3.0.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
constraintlayout = "2.2.1"
media = "1.7.1"
multidex = "2.0.1"
navigationFragment = "2.9.6"
navigationUi = "2.9.6"
pagingRuntime = "3.3.6"
palette = "1.0.0"
preference = "1.2.1"
recyclerview = "1.4.0"
roomCompiler = "2.8.3"
systembartint = "1.0.4"
workRuntime = "2.11.0"

[libraries]
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "pagingRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomCompiler" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
core = { module = "androidx.core:core", version.ref = "core" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
jaudiotagger = { module = "net.jthink:jaudiotagger", version.ref = "jaudiotagger" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
media = { module = "androidx.media:media", version.ref = "media" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
palette = { module = "androidx.palette:palette", version.ref = "palette" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
systembartint = { module = "com.readystatesoftware.systembartint:systembartint", version.ref = "systembartint" }
work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

